name = "exchange-rate-crawler"
main = "main.py"
compatibility_date = "2024-03-18"
compatibility_flags = ["python_workers"]

# 定时任务配置 - 每4分钟执行一次
[triggers]
crons = ["*/4 * * * *"]

# 环境变量
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.dev]
name = "exchange-rate-crawler-dev"
[env.dev.vars]
ENVIRONMENT = "development"

# 生产环境配置
[env.production]
name = "exchange-rate-crawler-prod"
[env.production.vars]
ENVIRONMENT = "production" 