name = "exchange-rate-dashboard"
compatibility_date = "2024-12-25"

[env.production]
account_id = "YOUR_ACCOUNT_ID"

# Pages配置
[pages_build_output_dir]
pages_build_output_dir = "."

# 环境变量（可选）
[vars]
API_ENDPOINT = "https://exchange-rate-worker.YOUR_SUBDOMAIN.workers.dev" 